### ISSUE TITLE
Compatibility test cases

### ISSUE THREAD

**Issue by dgryski** [ericherman/libjumphash#1]
The Jump Hash was originally releases as part of Guava.  I have a port of those tests if you want to check for compatibility with other implementations.

https://github.com/dgryski/go-jump/blob/master/jump_test.go#L30

**Comment by ericherman** [comment]
I took a quick browse and didn't see those Guava tests. I'm probably overlooking them. In addition to your port, do you have a pointer to the originals, too?

**Comment by dgryski** [comment]
The Guava tests for Jump Hash were ported from 

https://github.com/google/guava/blob/master/guava-tests/test/com/google/common/hash/HashingTest.java#L230

**Comment by ericherman** [comment]
Great! Thanks!
